//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowerShop.Application.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт не существует.
        /// </summary>
        public static string DoNotExsistProduct {
            get {
                return ResourceManager.GetString("DoNotExsistProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория продукта не существует.
        /// </summary>
        public static string DoNotExsistProductCategory {
            get {
                return ResourceManager.GetString("DoNotExsistProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение не существует.
        /// </summary>
        public static string DoNotExsistProductImage {
            get {
                return ResourceManager.GetString("DoNotExsistProductImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верный пароль. Попробуйте еще раз.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин уже существует.
        /// </summary>
        public static string LoginAlreadyExists {
            get {
                return ResourceManager.GetString("LoginAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество изображений не должно превышать 3 штуки .
        /// </summary>
        public static string MaxImageLength {
            get {
                return ResourceManager.GetString("MaxImageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должно быть хотя бы одно изображение.
        /// </summary>
        public static string MinImageLength {
            get {
                return ResourceManager.GetString("MinImageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлы не должны совпадать.
        /// </summary>
        public static string NotUniqueFiles {
            get {
                return ResourceManager.GetString("NotUniqueFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл  должен содержать изображение .
        /// </summary>
        public static string NotValidFile {
            get {
                return ResourceManager.GetString("NotValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукт с таким названием уже существует.
        /// </summary>
        public static string ProductExsict {
            get {
                return ResourceManager.GetString("ProductExsict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователя с логином &apos;{0}&apos; не найден.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
